version: '3.3'
services:
  backend:
    container_name: backend
    build: ./simple-api
    restart: always #on met le restart ici, pour sécuriser le lancement du backend après la BD
    networks:
      - app-network
    depends_on: #pour démarrer après un autre conteneur (limité car database prend trop de temps, l'appli va crash)
      - database

  database:
    container_name: database
    build: ./database
    networks:
      - app-network
    env_file: #fichiers de config
      - database/.env

  httpd:
    container_name: reverse_proxy
    build: ./httpd
    ports:
      - "80:80"
    networks:
      - app-network

  frontend:
    container_name: frontend
    build: ./devops-front-main
    ports:
      - 4200:80
    networks:
      - app-network


volumes:
  my_db_volume:
    driver: local

networks: #déclaration du network
  app-network:


